### ISSUE TITLE
store: decide on encoding

### ISSUE THREAD

**Issue by liamsi** [lazyledger/optimint#45]
Decide which encoding to use when serializing into the local data store.

ref: https://github.com/lazyledger/optimint/pull/42#discussion_r618225257

**Comment by tzdybal** [comment]
This encoding is important also for DA layer submission.

**Comment by tzdybal** [comment]
Some options for efficient serialization:
* protobuf - well known and widely used in cosmos ecosystem
* [Apache Avro](https://avro.apache.org/)

**Comment by tzdybal** [comment]
This issue was resolved by https://github.com/lazyledger/optimint/pull/57 - we decided to use protobuf.
